### ISSUE TITLE
Only show notifications checkbox when we are online.

### ISSUE THREAD

**Issue by tomayac** [pwassemble/pwassemble#1]

**Comment by vitaliy-bobrov** [comment]
@tomayac, what is the reason to show it only online?
imho better workflow:
- user toggle notifications when device is offline
- app shows message that notifications will be enabled after device will be online
- app waits for online mode and sends request
- app notifies user that notifications have been enabled

**Comment by tomayac** [comment]
As notifications trigger a system-level permission dialog, I think it really should be with immediate feedback. Else, you risk watering up the permission system if people forget that they signed up for this.
